routes/web.php
<?php

use App\Http\Controllers\Old as Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('tickets', Controllers\TicketsController::class)->names('tickets');
Route::post('subcategoria', [Controllers\TicketsController::class, 'subcategoria'])->name('subcategoria.post');
Route::post('area', [Controllers\TicketsController::class, 'area'])->name('area.post');

app/Models/Tickets.php
<?php

namespace App\Models;

use Illuminate\Support\Str;
use App\Scopes\TicketsByRole;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Tickets extends Model
{
    use HasFactory;
    /**
     * Conexión a utilizar
     *
     * @var string
     */
    protected $connection = 'tickets';

    /**
     * Nombre de la tabla a utilizar.
     *
     * @var string
     */
    protected $table = 'tickets';

    /**
     * Llave primaria a utilizar.
     *
     * @var string
     */
    protected $primaryKey = 'id';


    /**
     * Los atributos que son asignables en masa.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    /**
     * Attributes
     */
    protected $appends = [
        //
    ];

    /**
     * Carpeta Evidencia Inicial
     *
     * @return String|null $carpeta_evidencia_inicial
     */
    public function getCarpetaEvidenciaAttribute()
    {
        $tb_sucursal = TBSucursal::query()
            ->where('sucursal', $this->sucursal)
            ->first();

        if (!$tb_sucursal) {
            return null;
        }

        if (!$tb_sucursal->tb_app) {
            return null;
        }

        return $tb_sucursal->tb_app->carpeta;
    }

    /**
     * URL Evidencia Inicial
     *
     * @return String|null $url_evidencia
     */
    public function getUrlEvidenciaInicialAttribute()
    {
        if ($this->carpeta_evidencia == null) {
            return null;
        }

        $nombre_imagen = $this->evidenciaInicial;

        if ($this->ticket_sumapp != null) {
            $base = "https://fotos.sumapp.cloud/Sumapp";
        } else {
            $base = "https://fotostickets.sumapp.cloud";
        }

        return "{$base}/{$this->carpeta_evidencia}/{$nombre_imagen}";
    }

    /**
     * URL Evidencia Inicial
     *
     * @return String|null $url_evidencia
     */
    public function getUrlEvidenciaFinalAttribute()
    {
        if ($this->carpeta_evidencia == null) {
            return null;
        }

        $nombre_imagen = $this->evidenciaFinal;
        $base = "https://fotostickets.sumapp.cloud";

        return "{$base}/{$this->carpeta_evidencia}/{$nombre_imagen}";
    }

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::addGlobalScope('by_role', function (Builder $builder) {
            if (auth()->check()) {
                $auth = auth()->user();
                if (Str::contains($auth->rol_tickets, 'Corporativo')) {
                    $builder->where('empresa', $auth->empresa->c_nombre_empresa);
                } else {
                    $builder->where('sucursal', $auth->sucursal->sucursal);
                }
            }
        });
    }
}

app/Http/Controllers/Web/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Web\Dashboard;

use App\Helpers\SweetAlert2;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Tickets;

class DashboardController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
        //
    }

    /**
     * Retorna la vista de inicio
     *
     * @return View dashboard.inicio
     */
    public function inicio()
    {
        $tickets = Tickets::get();
        $status = (object) [
            'abiertos'    => $tickets->where('estatus', 'Abierto')->count(),
            'en_proceso'  => $tickets->where('estatus', 'En proceso')->count(),
            'cerrados'    => $tickets->where('estatus', 'Cerrado')->count(),
            'preventivos' => $tickets->where('accion', 'Preventivo')->count(),
            'correctivos' => $tickets->where('accion', 'Correctivo')->count()
        ];

        return view('dashboard.inicio', compact('status'));
    }
}

app/Http/Controllers/Web/Resources/TicketsController.php
<?php

namespace App\Http\Controllers\Web\Resources;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\{Areas, Controlcorreo, Correo, TBEmpresa, TBInventario, TCSSubcategorias, TCSCategorias, Tickets, TBSucursal};
use Illuminate\Support\Facades\{DB, File, Mail, Storage};
use App\Helpers;
use App\Mail\TicketcloseMail;
use App\Mail\TicketcreateMail;
use App\Rules\Auth;
use Illuminate\Support\Str;

class TicketsController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
        //
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tickets = Tickets::query()
            ->orderBy('id', 'DESC')
            ->get();

        return view('dashboard.tickets.index', compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sucursales = TBSucursal::get();
        $inventarios = TBInventario::get();

        $inventario = array();
        foreach ($inventarios as $inve) {
            $inv = $inve->inventario_nombre;

            array_push($inventario,  $inv);
        }
        $idSucursal = auth()->user()->id_sucursal;
       // $idSucursal = TBEmpresa::where('id_empresa', '10')->get();
       // $idSucursal->tcs_transmitio->get();
        $transmitio = DB::connection('tickets')->table('tcs_transmitio')
                    ->join('tcs_control_transmitio', 'tcs_transmitio.id', 'tcs_control_transmitio.idTransmitio')
                    ->select('tcs_transmitio.*')
                    ->where('tcs_control_transmitio.idSucursal', $idSucursal)
                    ->get();

        return view('dashboard.tickets.create', compact('sucursales', 'inventario', 'transmitio'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public static function store(Request $request)
    {




        $self = new Self;
        $request->validate([
            'sucursal'          => ['required', 'integer', 'exists:EV_SUMAPP.tb_sucursal,id_sucursal'],
            'area'              => ['required', 'integer', 'exists:tickets.areas,id'],
            'categoria'         => ['required', 'integer', 'exists:tickets.tcs_categorias,id'],
            'subcategoria'      => ['nullable', 'integer', 'exists:tickets.tcs_subcategorias,id'],
            'inventario'        => ['nullable', 'string'],
            'transmitio'        => ['nullable', 'string'],
            'cuarto'            => ['nullable', 'string'],
            'accion_a_realizar' => ['nullable', 'string'],
            'descripcion'       => ['nullable', 'string'],
            'observaciones'     => ['nullable', 'string'],
            'costo_estimado'    => ['nullable', 'numeric'],
            'fecha_estimada'    => ['nullable', 'date'],
            'evidencia'         => ['nullable', 'file', 'image', 'mimes:jpg,jpeg,png']
        ]);

        $tb_sucursal = TBSucursal::where('id_sucursal', $request->sucursal)->first();
        $area = (Areas::where('id', $request->area)->first())->area_descripcion;
        $tcs_categoria = (TCSCategorias::where('id', $request->categoria)->first())->categoria_descripcion;
        if ($request->has('subcategoria') and $request->subcategoria != null) {
            $tcs_subcategoria = (TCSSubcategorias::where('id', $request->subcategoria)->first())->descripcion_subcategoria;
        }



        if ($request->hasFile('evidencia')) {

            $fileIden = $request->file('evidencia');
            $iden = Str::slug(config('app.name') . ' ' . now()) . $fileIden->getClientOriginalName();
            Storage::disk('evidencias')->put("{$iden}", File::get($fileIden));
            // $fileIden->move('/var/www/vhosts/app.polizaderentas.com/public/docs/'.$folio[0]->clave.'/dueno/', $iden);
            $url = 'evidencias/'.$iden;

        }
        $crear_ticket = Tickets::create([
            'empresa'            => $tb_sucursal->tb_empresa->c_nombre_empresa,
            'sucursal'           => $tb_sucursal->sucursal,
            'area'               => $area,
            'categoria'          => $tcs_categoria,
            'subcategoria'       => $tcs_subcategoria ?? null,
            'transmitio'         => $request->transmitio ?? null,
            'habitacion'         => $request->cuarto,
            'accion'             => $request->accion_a_realizar,
            'ticket_descripcion' => $request->descripcion,
            'observaciones'      => $request->observaciones,
            'costo_estimado'     => $request->costo_estimado,
            'fecha_estimada'     => $request->fecha_estimada,
            'estatus'            => 'Abierto',
            'prioridad'          => $request->prioridad,
            'inventario'         => $request->inventario ?? null,
            'tipo_ticket'        => $request->tipo_ticket ?? null,
            'evidenciaInicial' => $url ?? null
        ]);

        if (auth()->user()->id_empresa == 27) {


            $idSuc = auth()->user()->id_sucursal;
            $nombre = auth()->user()->nombre . ' ' . auth()->user()->apellido;
            $ultimo_ticket = Tickets::latest('id')->first();
            $idUser = auth()->user()->id_usuario;
            $ticket = $ultimo_ticket->id;
            $usuario = $nombre;
            $area = $area;
            $descripcion = $request->descripcion;
            $descripcionCorreo = "Usuario:" . $usuario . "<br>Area:" . $area . "<br>Descripción:" . $descripcion . "<br>";


            $grupoCorreo = Controlcorreo::query()
                ->where('idUser', $idUser)
                ->first();
            $correo = Correo::query()
                ->where('id', $grupoCorreo->idCorreo)
                ->first();

            if ($grupoCorreo->idCorreo == 6) {
                $curl = curl_init();



                curl_setopt_array($curl, array(

                    CURLOPT_URL => 'https://notificaciones.sumapp.cloud/api/enviarnotificacion',

                    CURLOPT_RETURNTRANSFER => true,

                    CURLOPT_ENCODING => '',

                    CURLOPT_MAXREDIRS => 10,

                    CURLOPT_TIMEOUT => 0,

                    CURLOPT_FOLLOWLOCATION => true,

                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,

                    CURLOPT_CUSTOMREQUEST => 'POST',

                    CURLOPT_POSTFIELDS => 'grupo=' . $correo->descripcion_grupo . '&empresa=Empresa%20Virtual&titulo=Ticket#' . $ticket . '&tipo=Correo&descripcion=' . $descripcionCorreo . '&url=',

                    CURLOPT_HTTPHEADER => array(

                        'Authorization: Bearer 869ec6fe2bb0c3e8d160c084a8c722382ca850135b27096485b5e7c0bd62db93',

                        'Content-Type: application/x-www-form-urlencoded',

                        'Cookie: XSRF-TOKEN=eyJpdiI6IkY3Ti9LSDd4Tlk4Ky85N2t1dTBoUWc9PSIsInZhbHVlIjoiM3l1b2huaThvMnJsU2ZBQksyVXF6MWRCV21KaU0xSk1UZ0JXQjBCRFozRU9FTE9EVUx0Z3p6K1dnaUdKWjc4YjRoZC9aOHl6Ykg0bFQyc3Vzbk44YSsreVhMeHBKa216OGE5Y0FyTFNWMHRTQ1AzMUxkUzBNcmlxTUJHODBWQloiLCJtYWMiOiI0NmNjMWFlMzVkZjE2NTVjMGZkNzM2M2I4NjI4NDczNzBkZjM4OGU2YWY0Y2QwMWRlNDdkMWY5ZGQ1MGM2ZmVkIiwidGFnIjoiIn0%3D; notificaciones_sumapp_session=eyJpdiI6Ims4SHJmK3hBRjBrUldaUFF0eG90MUE9PSIsInZhbHVlIjoiMmRzOVowamRVUUJXeWErWldpUXJOTFlDNnRvRDlFaGdlREV3K2V1TFJ0cm1VcEs1UTEzOElIZEViTWlKN3VhRDc3cGZ2NEVNL2JsNTJhTWdMYWpTOFZiRkpuQit4a3haNCtWbFVQdFk3V2tabGU1bjIreHlFMVFXemd2UFp6WGMiLCJtYWMiOiIxOWU0YmUxMWM2MGNkZWJkNGE1NTljYzhkOTE0ZDJiYjRlZjY1MmU3MTNlMjA5MTg5NTRiYThiNDIzZThkNzAyIiwidGFnIjoiIn0%3D'

                    ),

                ));



                $response = curl_exec($curl);



                curl_close($curl);
            }else{

                $curl = curl_init();



                curl_setopt_array($curl, array(

                    CURLOPT_URL => 'https://notificaciones.sumapp.cloud/api/enviarnotificacion',

                    CURLOPT_RETURNTRANSFER => true,

                    CURLOPT_ENCODING => '',

                    CURLOPT_MAXREDIRS => 10,

                    CURLOPT_TIMEOUT => 0,

                    CURLOPT_FOLLOWLOCATION => true,

                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,

                    CURLOPT_CUSTOMREQUEST => 'POST',

                    CURLOPT_POSTFIELDS => 'grupo=' . $correo->descripcion_grupo . '&empresa=Empresa%20Virtual&titulo=Ticket#' . $ticket . '&tipo=Correo&descripcion=' . $descripcionCorreo . '&url=',

                    CURLOPT_HTTPHEADER => array(

                        'Authorization: Bearer 869ec6fe2bb0c3e8d160c084a8c722382ca850135b27096485b5e7c0bd62db93',

                        'Content-Type: application/x-www-form-urlencoded',

                        'Cookie: XSRF-TOKEN=eyJpdiI6IkY3Ti9LSDd4Tlk4Ky85N2t1dTBoUWc9PSIsInZhbHVlIjoiM3l1b2huaThvMnJsU2ZBQksyVXF6MWRCV21KaU0xSk1UZ0JXQjBCRFozRU9FTE9EVUx0Z3p6K1dnaUdKWjc4YjRoZC9aOHl6Ykg0bFQyc3Vzbk44YSsreVhMeHBKa216OGE5Y0FyTFNWMHRTQ1AzMUxkUzBNcmlxTUJHODBWQloiLCJtYWMiOiI0NmNjMWFlMzVkZjE2NTVjMGZkNzM2M2I4NjI4NDczNzBkZjM4OGU2YWY0Y2QwMWRlNDdkMWY5ZGQ1MGM2ZmVkIiwidGFnIjoiIn0%3D; notificaciones_sumapp_session=eyJpdiI6Ims4SHJmK3hBRjBrUldaUFF0eG90MUE9PSIsInZhbHVlIjoiMmRzOVowamRVUUJXeWErWldpUXJOTFlDNnRvRDlFaGdlREV3K2V1TFJ0cm1VcEs1UTEzOElIZEViTWlKN3VhRDc3cGZ2NEVNL2JsNTJhTWdMYWpTOFZiRkpuQit4a3haNCtWbFVQdFk3V2tabGU1bjIreHlFMVFXemd2UFp6WGMiLCJtYWMiOiIxOWU0YmUxMWM2MGNkZWJkNGE1NTljYzhkOTE0ZDJiYjRlZjY1MmU3MTNlMjA5MTg5NTRiYThiNDIzZThkNzAyIiwidGFnIjoiIn0%3D'

                    ),

                ));



                $response = curl_exec($curl);



                curl_close($curl);

                $curl = curl_init();



                curl_setopt_array($curl, array(

                    CURLOPT_URL => 'https://notificaciones.sumapp.cloud/api/enviarnotificacion',

resources/views/dashboard/tickets/index.blade.php
@extends('adminlte::page')
@section('title', 'Dashboard')

@section('content_header')
    <h1>Listado de Tickets</h1>
@stop

@section('content')
    <div class="pb-2">
        <div class="card">
            <div class="card-body">
                <x-datatable id="ticketsIndex" :disableSort="[7]">
                    <thead>
                        <tr>
                            <th>Folio</th>
                            <th>Estatus</th>
                            <th>Sucursal</th>
                            <th>Area</th>
                            <th>Categoría</th>
                            <th>Creación</th>
                            <th>Actualización</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($tickets as $ticket)
                            <tr>
                                <td>{{ "#{$ticket->id}" }}</td>
                                <td>{{ $ticket->estatus }}</td>
                                <td>{{ $ticket->sucursal ?? 'No aplica' }}</td>
                                <td>{{ $ticket->area ?? 'No aplica' }}</td>
                                <td>{{ $ticket->categoria ?? 'No aplica' }}</td>
                                <td>{{ $ticket->created_at ?? 'Desconocido' }}</td>
                                <td>{{ $ticket->updated_at ?? 'Ninguna' }}</td>
                                <td>
                                    <a class="btn btn-info btn-sm"
                                        href="{{ route('web.dashboard.tickets.show', ['ticket' => $ticket->id]) }}">
                                        <i class="far fa-eye"></i>
                                    </a>

                                    @if (auth()->user()->rol_tickers != 'Usuario')
                                        @if ($ticket->estatus != 'Cierre final')
                                            @if (!(auth()->user()->rol_tickets == 'Ejecutor' and $ticket->estatus == 'Cerrado'))
                                                <a class="btn btn-primary btn-sm"
                                                    href="{{ route('web.dashboard.tickets.edit', ['ticket' => $ticket->id]) }}">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                            @endif
                                        @endif
                                    @endif

                                    @if (auth()->user()->rol_tickets == 'Administrador')
                                        <button type="button" onclick="eliminarItem('{{ $ticket->id }}')"
                                            class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                        <form id="formDeleteTicket{{ $ticket->id }}" class="hide"
                                            action="{{ route('web.dashboard.tickets.destroy', ['ticket' => $ticket->id]) }}"
                                            method="POST">
                                            @csrf @method('delete')
                                        </form>
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </x-datatable>
            </div>
        </div>
    </div>
@stop

@section('css')
    <style>
        .hide {
            display: none;
        }
    </style>
@stop

@section('js')
    <script>
        function eliminarItem(idTicket) {
            Swal.fire({
                icon: 'question',
                title: '¿Deseas continuar?',
                text: `Estás a punto de eliminar el ticket #${idTicket}, ten en cuenta que esta acción es permanente`,
                confirmButtonText: 'Si, continuar',
                showCancelButton: true,
                cancelButtonText: 'Cancelar',
            }).then((res) => {
                if (res.isConfirmed) {
                    Loader.show();
                    $(`#formDeleteTicket${idTicket}`).submit();
                }
            });
        }
    </script>
@stop

resources/views/dashboard/tickets/show.blade.php
@extends('adminlte::page')
@section('title', 'Dashboard')

@section('content_header')
    <h1>Ver Ticket</h1>
@stop

@section('content')
    <div class="pb-2">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 col-md-4 mb-3">
                        <x-form.input label="Folio" model="folio" :value="'#'.$ticket->id" disabled />
                    </div>
                    <div class="col-12 col-md-4 mb-3">
                        <x-form.input label="Creación" model="creacion" :value="$ticket->created_at ?? 'Desconocido'" disabled />
                    </div>
                    <div class="col-12 col-md-4 mb-3">
                        <x-form.input label="Actualización" model="actualizacion" :value="$ticket->updated_at ?? 'Ninguna'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Estado" model="estatus" :value="$ticket->estatus ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Prioridad" model="prioridad" :value="$ticket->prioridad ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Sucursal" model="sucursal" :value="$ticket->sucursal ?? 'No aplica'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Area" model="area" :value="$ticket->area ?? 'No aplica'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Categoria" model="categoria" :value="$ticket->categoria ?? 'No aplica'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Subcategoria" model="subcategoria" :value="$ticket->subcategoria ?? 'No aplica'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Cuarto" model="cuarto" :value="$ticket->habitacion ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Acción a realizar" model="accion_a_realizar" :value="$ticket->accion ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.textarea label="Descripción" model="descripcion" disabled>{{ $ticket->ticket_descripcion ?? '[No hay información]' }}</x-form.textarea>
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.textarea label="Observaciones" model="observaciones" disabled>{{ $ticket->observaciones ?? '[No hay información]' }}</x-form.textarea>
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Costo estimado" model="costo_estimado" :value="$ticket->costo_estimado ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Fecha estimada" model="fecha_estimada" :value="$ticket->fecha_estimada ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Costo real" model="costo_real" :value="$ticket->costo ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <x-form.input label="Fecha real" model="fecha_real" :value="$ticket->fecha ?? '[No hay información]'" disabled />
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <div>
                            <label class="mb-2">Evidencia de falla:</label>
                            @if ($ticket->evidenciaInicial != null)
                                <img class="img-fluid rounded" src="{{ $ticket->url_evidencia_inicial }}">
                            @else
                                <div class="font-italic">[No hay evidencia]</div>
                            @endif
                        </div>
                    </div>
                    <div class="col-12 col-md-6 mb-3">
                        <div>
                            <label class="mb-2">Evidencia de solución:</label>
                            @if ($ticket->evidenciaFinal != null)
                                <img class="img-fluid rounded" src="{{ $ticket->url_evidencia_final }}">
                            @else
                                <div class="font-italic">[No hay evidencia]</div>
                            @endif
                        </div>
                    </div>
                    <div class="col-12">
                        <hr>
                        <div class="text-left">
                            <a class="btn btn-info" href="{{ route('web.dashboard.tickets.index') }}">
                                <i class="fas fa-angle-left"></i> Regresar
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop